---
title: "HAC1ends"
output: html_document
date: '2022-03-20'
---
```{r}
library(tidyverse)
library(patchwork)
library(cowplot)
library(here)
library(fs)

# get file names
# use fs::dir_ls() & here() to replace list.file pattern globbing
pos_files = dir_ls(path = here('data/mRNA_plusminus_Xrn1_bgs/'))

# here's a function to read in all the bed files in the specified path
read_file <- function(x) {
  df <- readr::read_tsv(x, col_names = c("ref", "pos", "end", "count"))
  df$name <- basename(x)
  
  df
}

pos_table <- purrr::map_df(pos_files, read_file) 
pos_table %>%
  separate(name, into = c("p", "strand", "id", "treatment", "Exo"), sep = "_") %>%
  select(-end, -p, -strand) %>%
  separate(Exo, into = c("exo"), sep = "\\.", extra = "drop") -> all_5p_ends

```
Raw counts data:
```{r}
scales_y <- list(
  
)

all_5p_ends %>%
  filter(exo == "Xrn1" & ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = count, fill = id)) +
  geom_col(width = 5) +
  scale_x_continuous(breaks = seq(0, 1198, by = 150), expand = c(0, .5)) +
  facet_wrap(id~treatment, ncol = 1, strip.position = "right") + # formerly scales = "free_y" for preprint
  coord_cartesian(ylim = c(0,200)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf) + # fake x axis on all 
  theme(aspect.ratio = 1/4) -> a

all_5p_ends %>%
  filter(exo == "NoExo" & ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = count, fill = id)) +
  geom_col(width = 5) +
  scale_x_continuous(breaks = seq(0, 1198, by = 150), expand = c(0, .5)) +
  facet_wrap(id~treatment, ncol = 1, strip.position = "right") +
  coord_cartesian(ylim = c(0,200)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf) + # fake x axis on all 
  theme(aspect.ratio = 1/4) -> b

plot_grid(b, a)
ggsave("rev1F.png")
```
Need to make 1F (used to be in fig 2, moved around since) with just the +tm data.
```{r}
all_5p_ends %>%
  filter(treatment == "Tm" & id == "CRY1") %>%
  select(-treatment, id) %>%
  pivot_wider(., names_from = exo, values_from = count, values_fill = 0) %>%
  mutate(delta = Xrn1 - NoExo) -> wt 
  
all_5p_ends %>%
  filter(treatment == "Tm" & id == "xrn1tpt1") %>%
  select(-treatment, id) %>%
  pivot_wider(., names_from = exo, values_from = count, values_fill = 0) %>%
  mutate(delta = Xrn1 - NoExo) -> mt 
 
bind_rows(wt, mt) -> xrn1_delta

wt %>%
  select(-NoExo, -Xrn1, -id) %>%
  rename(wtdelt = delta) -> HAC1wt

mt %>%
  select(-NoExo, -Xrn1, -id) %>%
  rename(mtdelt = delta) -> HAC1mt

full_join(HAC1wt, HAC1mt, by = c("ref", "pos"), values_fill) %>%
  replace_na(list(mtdelt = 0, wtdelt = 0)) %>%
  mutate(delta = mtdelt - wtdelt) -> diffdiff

# how many RNAs have positions with >=30CPM difference of differences? 59. >= 50? 25.
diffdiff %>%
  filter(mtdelt > 9 & pos > 19 & delta > 24.99) %>%
  distinct(ref) -> distinct

```
plot things
```{r}
# to reuse for generating figure plot, make same as full2 below
xrn1_delta %>%
  filter(ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = delta, fill = id)) +
  geom_col(width = 5) +
  scale_x_continuous(breaks = seq(0, 1198, by = 300), expand = c(0, .5)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) -> full1

```

```{r}
xrn1_delta %>%
  filter(ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = delta, fill = id)) +
  geom_col(width = 1) +
  scale_x_continuous(breaks = seq(0, 1198, by = 10), expand = c(0, .5)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(xlim = c(700, 750), ylim = c(-50, 170)) -> zoom1

```

```{r}
diffdiff %>%
  filter(ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = delta)) +
  geom_col(width = 5) +
  scale_x_continuous(breaks = seq(0, 1198, by = 300), expand = c(0, .5)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) -> full2

diffdiff %>%
  filter(ref == "YFL031W_mRNA") %>%
  ggplot(., aes(x = pos, y = delta)) +
  geom_col(width = 1) +
  scale_x_continuous(breaks = seq(0, 1198, by = 10), expand = c(0, .5)) +
  theme_cowplot() +
  scale_fill_manual(values = c(CRY1 = "#56B4E9", xrn1tpt1="#E69F00")) +
  theme(legend.position = "none") +
  labs(title = "",
       x = "",
       y = "",
       fill = "") +
  theme(strip.text.y = element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(xlim = c(700, 750), ylim = c(-10, 170)) -> zoom2

full1 + zoom1 + full2 + zoom2 + 
  plot_layout(widths = c(10, 3), heights = c(2, 2)) #+ theme(plot.margin = c(1,1,1,1))

ggsave("hac1ends.pdf", width = 10, height = 4)
```

